---
# yaml-language-server: $schema=https://schema.blue-build.org/stage-list-v1.json

stages:
  - name: build-dash-to-panel
    from: build-base
    modules:
      - type: git
        source: local
        repo: https://github.com/TiamoP23/dash-to-panel.git
        branch: copilot/check-taskbar-hidden-overview
        dest: /dash-to-panel
      - type: script
        snippets:
          - cd /dash-to-panel && make _build
  - name: build-blur-my-shell
    from: build-base
    modules:
      - type: git
        source: local
        repo: https://github.com/TiamoP23/blur-my-shell.git
        branch: master
        dest: /blur-my-shell
      - type: script
        snippets:
          - cd /blur-my-shell && make build
  - name: build-clipboard-indicator
    from: build-base
    modules:
      - type: git
        source: local
        repo: https://github.com/TiamoP23/gnome-shell-extension-clipboard-indicator.git
        branch: master
        dest: /clipboard-indicator
      - type: script
        snippets:
          - cd /clipboard-indicator && make bundle