---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
  - type: gnome-extensions
    install:
      - Dash to Panel
  - type: dnf
    install:
      packages:
        - hydrapaper
  - type: containerfile
    snippets:
      - |
        RUN \
          --mount=from=build-blur-my-shell,source=/blur-my-shell/build/blur-my-shell@aunetx.shell-extension.zip,target=/tmp/blur-my-shell.zip \
          unzip -o /tmp/blur-my-shell.zip -d /usr/share/gnome-shell/extensions/blur-my-shell@aunetx && \
          glib-compile-schemas /usr/share/gnome-shell/extensions/blur-my-shell@aunetx/schemas