---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        install:
          - io.podman_desktop.PodmanDesktop
  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      packages:
        - podman-compose
        - code
  - type: files
    files:
      - source: system/etc/skel
        destination: /etc/skel
  - type: script
    scripts:
      - install-devcontainers-extension.sh